#!/usr/bin/python

import ram.wizards


if __name__ == '__main__':
    params = ram.param()

    try:
        timeout = int(params.timeout) if params.timeout else 0
    except Exception:
        raise SystemExit("Parameter `timeout` should be an int value.")

    try:
        message = str(params.message) if params.message else None
    except Exception:
        pass

    try:
        shell = str(params.shell) if params.shell else True
    except Exception:
        pass

    try:
        ram.wizards.pause(message=message, timeout=timeout, shell=shell)
    except OverflowError:
        raise SystemExit(1)
    except KeyboardInterrupt:
        raise SystemExit(2)
