#!/usr/bin/python

import ram.context
import ram.widgets


with ram.context(__name__):
    from wiz.entry import UnitEntry

if __name__ == '__main__':
    params = ram.param()
    isfqdn = 'fqdn' if params.fqdn else 'nofqdn'

    if params.wizard:
        ram.widgets.RunList(
            [
                UnitEntry('net.hostname', 'forced', 'erased', isfqdn, apply=False),
                UnitEntry('net.ifconfig', 'wizard', apply=False, pause=False),
                UnitEntry('net.routing', 'wizard', apply=False),
                UnitEntry('net.resolver', 'wizard', apply=False),
            ]
        )
    else:
        ram.widgets.RunMenu(
            "Select action",
            [
                ("Interface configuration ...", UnitEntry('net.ifconfig', apply=False)),
                ("", 0),
                ("Routing configuration ...", UnitEntry('net.routing', apply=False)),
                ("Change the system hostname ...", UnitEntry('net.hostname', isfqdn, apply=False)),
                ("DNS resolver configuration ...", UnitEntry('net.resolver', apply=False)),
            ]
        )
