#!/usr/bin/python

import ram.context


with ram.context(__name__):
    from entry import RunDnsConfigurationMenu
    from entry import RemovePeerDnsDevice
    from entry import ModifyPeerDnsDevice
    from entry import CompatPeerDnsConfig


if __name__ == '__main__':
    config = ram.query('net.network')
    params = ram.param()

    if not CompatPeerDnsConfig(config):
        raise SystemExit()

    if not params.device:
        RunDnsConfigurationMenu(config, params.wizard)
    elif params.device == "no":
        RemovePeerDnsDevice(config, edit_address=True)
    elif params.device:
        ModifyPeerDnsDevice(config, params.device)

    ram.store('net.network', input=config)
