#!/usr/bin/python

import ram.context


with ram.context(__name__):
    from entry import RunDnsConfigurationMenu
    from entry import EditIfaceDnsServers
    from entry import ModifyPeerDnsDevice


if __name__ == '__main__':
    config = ram.query('net.network')
    params = ram.param()

    if not params.device:
        RunDnsConfigurationMenu(config, params.wizard)
    elif params.device == "no":
        EditIfaceDnsServers(config)
    elif params.device:
        ModifyPeerDnsDevice(config, params.device)

    ram.store('net.network', input=config)
