#!/usr/bin/python

import ram.context
import ram.symbols

with ram.context(__name__):
    from .utils import ListPeerDnsDevices


if __name__ == '__main__':
    config = ram.query('net.network')

    for ifname in config['ifconfig']:
        config['resolver'][ifname]['enabled'] = config['ifconfig'][ifname]['enabled']
        config['resolver'][ifname]['usedhcp'] = config['ifconfig'][ifname]['usedhcp']

    config['resolver']['ifaces'] = " ".join(sorted(ListPeerDnsDevices(config['ifconfig'])))

    ram.symbols.send(config['resolver'])
