#!/usr/bin/python -u

import sys
import select

import ram


def drain():
    while select.select([sys.stdin], [], [], 0) == ([sys.stdin], [], []):
        sys.stdin.read(1)


def write(s):
    sys.stdout.write(s)
    sys.stdout.flush()


if __name__ == '__main__':
    params = ram.param()

    try:
        wait = int(params.wait) if params.wait else 0
    except Exception:
        raise SystemExit("Parameter `wait` should be an int value.")

    text = params.text or "Press ENTER to continue"

    try:
        drain()

        write(text + ('' if wait else ':'))

        tout = 1 if wait else 0

        while not tout or wait:
            if select.select([sys.stdin], [], [sys.stdin], tout) == ([sys.stdin], [], []):
                break
            if tout:
                write('.')
            wait -= tout
    except KeyboardInterrupt:
        raise SystemExit(1)
    finally:
        write('\n')
        drain()
