#!/usr/bin/python

import ram.context


with ram.context(__name__):
    from entry import RoutesConfigurationMenu
    from entry import RemoveGatewayDevice
    from entry import ModifyGatewayDevice


if __name__ == '__main__':
    config = ram.query()
    params = ram.param()

    if not params.device:
        RoutesConfigurationMenu(config, params.wizard)
    elif params.device == "no":
        RemoveGatewayDevice(config)
    elif params.device:
        ModifyGatewayDevice(config, params.device)

    ram.store(input=config)
