#!/usr/bin/python

import ram.symbols
import ram.context

with ram.context(__name__):
    from .utils import ListGatewayDevices

if __name__ == '__main__':
    config = ram.query('net.network')

    for ifname in config['ifconfig']:
        config['routing'][ifname]['enabled'] = config['ifconfig'][ifname]['enabled']
        config['routing'][ifname]['usedhcp'] = config['ifconfig'][ifname]['usedhcp']
        config['routing'][ifname]['ignored'] = config['ifconfig'][ifname]['ignored']
        config['routing'][ifname]['gateway'] = config['ifconfig'][ifname]['gateway']

    config['routing']['ifaces'] = " ".join(sorted(ListGatewayDevices(config['ifconfig'])))

    ram.symbols.send(config['routing'])
