#!/usr/bin/python

import libuser

import ram.symbols


if __name__ == '__main__':
    config = ram.symbols()

    _dbapi = libuser.admin()

    admins = [_ for _ in _dbapi.enumerateUsersFull() if _[libuser.GECOS][0] == "#"]
    _chars = len(str(len(admins)))

    for _, user in enumerate(admins):
        _index = '_%.*i' % (_chars, _)

        config['admins'][_index]['login'] = user[libuser.USERNAME][0]
        config['admins'][_index]['shell'] = user[libuser.LOGINSHELL][0]

        passwd = ([''] + user.get(libuser.USERPASSWORD)).pop()
        shadow = ([''] + user.get(libuser.SHADOWPASSWORD)).pop()

        config['admins'][_index]['passwd'] = (
            passwd if passwd and passwd[0] == "$" else
            shadow if shadow and shadow[0] == "$" else
            ""
        )

        config['admins'][_index]['groups'] = " ".join(_dbapi.enumerateGroupsByUser(user[libuser.USERNAME][0]))

    config['exists'] = " ".join(_dbapi.enumerateUsers())

    ram.symbols.send(config)
