#!/usr/bin/python

import libuser

import ram.symbols


if __name__ == '__main__':
    config = ram.symbols.recv()
    _dbapi = libuser.admin()

    for _index in config['admins']:
        _admin = config['admins'][_index]

        user = _dbapi.lookupUserByName(_admin['login'])
        if not user:
            user = _dbapi.initUser(_admin['login'])
            _dbapi.addUser(user, mkhomedir=True, mkmailspool=True)

        group = _dbapi.lookupGroupByName(_admin['login'])
        if not group:
            group = _dbapi.initGroup(_admin['login'])
            _dbapi.addGroup(group)

        user[libuser.GECOS] = "#"
        user[libuser.GIDNUMBER] = group[libuser.GIDNUMBER]
        user[libuser.LOGINSHELL] = _admin['shell']

        for groupname in config['groups'].split():
            group = _dbapi.lookupGroupByName(groupname)
            if not group:
                group = _dbapi.initGroup(groupname)
                _dbapi.addGroup(group)
            group.add(libuser.MEMBERNAME, _admin['login'])
            _dbapi.modifyGroup(group)

        _dbapi.modifyUser(user)

        _dbapi.setpassUser(user, _admin['passwd'], is_crypted=True)

    admins = [config['admins'][_]['login'] for _ in config['admins']]

    for user in _dbapi.enumerateUsersFull():
        if not user[libuser.GECOS][0] == "#":
            continue

        if user[libuser.USERNAME][0] in admins:
            continue

        group = _dbapi.lookupGroupByName(user[libuser.USERNAME][0])
        if group:
            _dbapi.deleteGroup(group)

        if user:
            _dbapi.deleteUser(user, rmhomedir=True, rmmailspool=True)
