#!/usr/bin/python

import ram.symbols
import ram.context


with ram.context(__name__):
    from net.ifcfg import QueryNetworkConfiguration
    from net.ifcfg import StoreNetworkConfiguration


if __name__ == '__main__':
    config = ram.symbols.recv()
    netcfg = QueryNetworkConfiguration()

    # ifconfig
    for ifname in config['ifconfig']:
        if ifname in netcfg:
            continue
        if config['ifconfig'][ifname]['defconf']:
            continue
        netcfg.AddIface(ifname)

    for ifname in netcfg:
        if netcfg.IsLoopback(ifname):
            continue
        if not config['ifconfig'][ifname]['defconf']:
            continue
        netcfg.DelIface(ifname)

    for ifname in netcfg:
        if netcfg.IsLoopback(ifname):
            continue
        netcfg.SetIfaceDevName(ifname, config['ifconfig'][ifname]['devname'])
        netcfg.SetIfaceEnabled(ifname, config['ifconfig'][ifname]['enabled'])
        netcfg.SetIfaceUseDhcp(ifname, config['ifconfig'][ifname]['usedhcp'])
        netcfg.SetIfaceIpAddress(ifname, config['ifconfig'][ifname]['ip_addr'])
        netcfg.SetIfaceIpNetmask(ifname, config['ifconfig'][ifname]['netmask'])
        netcfg.SetIfaceGwIgnored(ifname, config['ifconfig'][ifname]['ignored'])
        netcfg.SetIfaceIpGateway(ifname, config['ifconfig'][ifname]['gateway'])
        netcfg.SetIfacePeerDns(ifname, config['ifconfig'][ifname]['peerdns'])
        netcfg.SetIfacePrimaryDns(ifname, config['ifconfig'][ifname]['pri_dns'])
        netcfg.SetIfaceSecondaryDns(ifname, config['ifconfig'][ifname]['sec_dns'])
        netcfg.SetIfaceSearchList(ifname, config['ifconfig'][ifname]['domains'])

    # routing
    default = config['routing']['default']
    netcfg.SetGatewayDevice(default)

    # resolver
    netcfg.SetPeerDnsDevice(config['resolver']['peerdns'])
    netcfg.SetIfacePrimaryDns(None, config['resolver']['pri_dns'])
    netcfg.SetIfaceSecondaryDns(None, config['resolver']['sec_dns'])
    netcfg.SetIfaceSearchList(None, config['resolver']['domains'])

    StoreNetworkConfiguration(netcfg)
